### PR TITLE
👩‍🌾 Fix flake8: specify exception

### PR DESCRIPTION
**Pull request by chapulina**
Refer to the docs:

https://docs.python.org/3/library/os.path.html#os.path.getmtime

https://github.com/osrf/buildfarmer/issues/145

### CODE REVIEW

**Review by cottsay — APPROVED** [review]

**Review by jacobperron — APPROVED** [review]

**Comment by chapulina** [comment]
Can someone merge this? Me no have powers in this realm.

**Comment by dirk-thomas** [comment]
@chapulina can you please share the exact error message this addresses (and in which environment, e.g. the flake extension version).

**Comment by chapulina** [comment]
This fixes the Travis CI provided by this repository:

* https://github.com/colcon/colcon-cmake/blob/master/.travis.yml
* https://travis-ci.org/github/colcon/colcon-cmake

```
----------------------------- Captured stderr call -----------------------------

/home/travis/build/colcon/colcon-cmake/colcon_cmake/event_handler/compile_commands.py:71:1: B902 blind except Exception: statement

            except Exception:

^

/home/travis/build/colcon/colcon-cmake/colcon_cmake/event_handler/compile_commands.py:77:1: B902 blind except Exception: statement

                    except Exception:

^

flake8 reported 2 errors

------------------------------ Captured log call -------------------------------
```

**Comment by jacobperron** [comment]
B902 was introduced in a recent version of  flake8-blind-except (https://github.com/elijahandrews/flake8-blind-except/pull/12). IMO, it's a bit overly restrictive and can be suppressed responsibly.

I've proposed a bunch of related PRs fixing CI in colcon repos:

- colcon/colcon-core#424
- colcon/colcon-metadata#27
- colcon/colcon-notification#51
- colcon/colcon-package-information#34
- colcon/colcon-ros#120

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
