### PR TITLE
fix return type

### PR DESCRIPTION
**Pull request by dirk-thomas**
Follow up of #32.

@paulbovbel FYI

### CODE REVIEW

**Comment by paulbovbel** [comment]
Isn't this basically what was there before https://github.com/colcon/colcon-cmake/commit/7ac46cc59032682babbb95ad2ba30c1f89b755fe?

**Comment by dirk-thomas** [comment]
No.

Initially it was checking for `if rc` which was always `True` since `rc` is an instance of `subprocess.CompletedProcess`. So the loop always stopped after the first target.

With the recent change I fixed the condition to check `if rc and rc.returncode` but by then returning `rc.returncode` the caller of the function wasn't happy which still expects that if something is returned it to be a `subprocess.CompletedProcess`.

**Comment by paulbovbel** [comment]
Thanks, I'll update our system once you cut a release.

**Comment by dirk-thomas** [comment]
> I'll update our system once you cut a release.

:ship:

**Comment by MatteoRagni** [comment]
May I suggest to update the title of this pull request with something a little more easy to find? Something like **Fix Return type (rc is of type int in build.py)**

**Pull request merged**
