### PR TITLE
use multiple processes by default with Visual Studio

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes colcon/colcon-core#57.

Custom parameters can still be passed by setting the environment variable `CL` (similar to `MAKEFLAGS` for Make).

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> What happens in the case where a user specify /m:2 ? Shouldn't we pass /MP2 (instead of just /MP) to respect the user specified value?

No, [/MP](https://msdn.microsoft.com/en-us/library/bb385193.aspx) only indicates to build with multiple processes. [/m:X](https://msdn.microsoft.com/en-us/library/ms164311.aspx) where `X` specifies the maximum number of concurrent processes.

**Comment by mikaelarguedas** [comment]
> No, /MP only indicates to build with multiple processes

From the /MP page you linked:
"If you omit the processMax argument, the compiler retrieves the number of effective processors on your computer from the operating system, and creates a process for each processor."
"The number argument of the /maxcpucount MSBuild option specifies the maximum number of projects to build at the same time. Similarly, the processMax argument of the /MP compiler option specifies the maximum number of compilation units to build at the same time. If the /maxcpucount option specifies P projects and the /MP option specifies C processes, a maximum of PxC processes execute at the same time."

**Comment by dirk-thomas** [comment]
I modified the condition to only check for `/MP` in https://github.com/colcon/colcon-cmake/pull/12/files#diff-af9d22be861287184d5eedb3f47a01daR212

**Comment by dirk-thomas** [comment]
One example build on Windows using all available cores: [Build Status](https://ci.ros2.org/job/ci_windows/4473/)

**Pull request merged**
